export const themes = [
  {
    id: 0,
    name: "Default",
    outer_text: "text-slate-900",
    inner_text: "text-white",
    dark: "bg-slate-900",
    medium: "bg-blue-950",
    light: "bg-slate-800",
    clear_bg: "bg-slate-300",
  },
  {
    id: 1,
    name: "Neutral",
    outer_text: "text-stone-900",
    inner_text: "text-white",
    dark: "bg-stone-900",
    medium: "bg-stone-800",
    light: "bg-neutral-900",
    clear_bg: "bg-stone-300",
  },
  {
    id: 2,
    name: "Colorful",
    outer_text: "text-black",
    inner_text: "text-white",
    dark: "bg-blue-950",
    medium: "bg-cyan-700",
    light: "bg-pink-900",
    clear_bg: "bg-pink-100",
  },
];
