export const themes = [
  {
    id: 0,
    name: "Warm Neutral",
    outer_text: "text-[#0a0701]",
    inner_text: "text-[#0a0701]",
    dark: "bg-[#f2e7e1]",
    medium: "bg-[#F2D7CA]",
    light: "bg-[#F5EEE6]",
    clear_bg: "bg-[#fcfaf7]",
    border: "border-[#F2D7CA]",
    hourglass: "#F2D7CA",
  },
  {
    id: 1,
    name: "True Neutral",
    outer_text: "text-black",
    inner_text: "text-black",
    dark: "bg-[#c9c8c1]",
    medium: "bg-[#E3E1D9]",
    light: "bg-[#F1EFE5]",
    clear_bg: "bg-[#f7f7f5]",
    border: "border-[#B4B4B8]",
    hourglass: "#B4B4B8",
  },
  {
    id: 2,
    name: "Light Pastel",
    outer_text: "text-[#02090a]",
    inner_text: "text-[#02090a]",
    dark: "bg-[#B5C0CF]",
    medium: "bg-[#CBD3CA]",
    light: "bg-[#DEDEDE]",
    clear_bg: "bg-[#ebeff5]",
    border: "border-[#B5C0CF]",
    hourglass: "#B5C0CF",
  },
  {
    id: 3,
    name: "Light Blue",
    outer_text: "text-[#030d1a]",
    inner_text: "text-[#030d1a]",
    dark: "bg-[#C8D8EB]",
    medium: "bg-[#a9bfd9]",
    light: "bg-[#ECF2F8]",
    clear_bg: "bg-[#e4ebf5]",
    border: "border-[#C8D8EB]",
    hourglass: "#C8D8EB",
  },
  {
    id: 4,
    name: "Gray Sky",
    outer_text: "text-[#02090a]",
    inner_text: "text-[#02090a]",
    dark: "bg-[#B3C7CF]",
    medium: "bg-[#BED7DC]",
    light: "bg-[#c1d5d9]",
    clear_bg: "bg-[#f2f9fa]",
    border: "border-[#B3C7CF]",
    hourglass: "#B3C7CF",
  },
  {
    id: 5,
    name: "Blueberry",
    outer_text: "text-[#040c17]",
    inner_text: "text-white",
    dark: "bg-[#243957]",
    medium: "bg-[#3e5d89]",
    light: "bg-[#465f82]",
    clear_bg: "bg-[#cad5e6]",
    border: "border-[#3e5d89]",
    hourglass: "#243957",
  },
  {
    id: 6,
    name: "Slate",
    outer_text: "text-slate-800",
    inner_text: "text-white",
    dark: "bg-slate-900",
    medium: "bg-[#151f38]",
    light: "bg-[#242e4a]",
    clear_bg: "bg-slate-300",
    border: "border-[#151f38]",
    hourglass: "#151f38",
  },
  {
    id: 7,
    name: "Steel teal",
    outer_text: "text-[#111a1c]",
    inner_text: "text-white",
    dark: "bg-[#455d61]",
    medium: "bg-[#627e82]",
    light: "bg-[#708f91]",
    clear_bg: "bg-[#ced9db]",
    border: "border-[#455d61]",
    hourglass: "#376343",
  },
  {
    id: 8,
    name: "Dark Sage",
    outer_text: "text-[#040E12]",
    inner_text: "text-white",
    dark: "bg-[#193D3D]",
    medium: "bg-[#5B8374]",
    light: "bg-[#87a89c]",
    clear_bg: "bg-[#e1f0ea]",
    border: "border-[#193D3D]",
    hourglass: "#193D3D",
  },
  {
    id: 9,
    name: "Moody",
    outer_text: "text-[#1E201E]",
    inner_text: "text-white",
    dark: "bg-[#1E201E]",
    medium: "bg-[#3C3D37]",
    light: "bg-[#687564]",
    clear_bg: "bg-[#dcded5]",
    border: "border-[#3C3D37]",
    hourglass: "#3C3D37",
  },
  {
    id: 10,
    name: "Dark Neutral",
    outer_text: "text-stone-900",
    inner_text: "text-white",
    dark: "bg-[#141313]",
    medium: "bg-[#1c1919]",
    light: "bg-stone-800",
    clear_bg: "bg-stone-300",
    border: "border-[#1c1919]",
    hourglass: "#1c1919",
  },
  {
    id: 11,
    name: "Sunset",
    outer_text: "text-black",
    inner_text: "text-[#f5ede9]",
    dark: "bg-[#c7616d]",
    medium: "bg-[#D2756B]",
    light: "bg-[#d18382]",
    clear_bg: "bg-[#f5ede9]",
    border: "border-[#A75D5D]",
    hourglass: "#A75D5D",
  },
  {
    id: 12,
    name: "Pink",
    outer_text: "text-[#12040a]",
    inner_text: "text-[#12040a]",
    dark: "bg-[#F1789F]",
    medium: "bg-[#F998B6]",
    light: "bg-[#F9C5D5]",
    clear_bg: "bg-[#ffedf2]",
    border: "border-[#F1789F]",
    hourglass: "#F1789F",
  },
  {
    id: 13,
    name: "Lilac",
    outer_text: "text-[#080114]",
    inner_text: "text-[#080114]",
    dark: "bg-[#ac94d6]",
    medium: "bg-[#645BAA]",
    light: "bg-[#BFACE0]",
    clear_bg: "bg-[#ece9f2]",
    border: "border-[#645BAA]",
    hourglass: "#645BAA",
  },
  {
    id: 14,
    name: "Purple",
    outer_text: "text-[#09030a]",
    inner_text: "text-[#f5ebf7]",
    dark: "bg-[#5A639C]",
    medium: "bg-[#7776B3]",
    light: "bg-[#9B86BD]",
    clear_bg: "bg-[#f5ebf7]",
    border: "border-[#7776B3]",
    hourglass: "#7776B3",
  },
];
